pipeline{
    environment{
        to = emailextrecipients([
                [$class: 'CulpritsRecipientProvider']
        ])
        subject = "${env.JOB_NAME} - Build #${env.BUILD_NUMBER} ${currentBuild.result}"
        content = '${JELLY_SCRIPT,template="html"}'

    }
  agent any
  stages{

      stage('Build'){
          steps{
            echo "building.... "
          }
      }
      stage('Test'){
          steps{
            echo 'Testing.... '
            sh 'make'
            echo "${currentBuild.result}"
            }
      }
      stage('Environment Variables'){
            steps{
                echo 'Displaying Environment Variables.... '
                echo "Running ${env.BUILD_ID} and ${env.BUILD_NUMBER} and ${env.JOB_NAME} on ${env.JENKINS_URL}"
            }
      }
      stage('Deploy'){
          when{
            expression{
                currentBuild.result == null || currentBuild.result == 'FAILURE'
                echo "${env.JOB_NAME} - Build# ${env.BUILD_NUMBER} ${currentBuild.result}"
            }
          }
          steps{
            echo 'deploying.... '
            echo currentBuild.result
          }
      }
  }
    post{
        always {
            echo 'run this anyway'
        }
        success {
            echo 'only on Build Successful'
        }
        failure {
                echo "${currentBuild.result}"
                expression {
                    to != null || !to.isEmpty()
                    emailtext(body:content, mimeType: 'text/html', subject: subject, to: to, attachLog: true)
                }
        }
    }
}


